"""Per-query latency table, and the change from a previous timing sweep.

    python -m sabermath.reporting.timing_tables --out results/tables/RESULTS_timing.md

Every model is timed on the SAME 50 queries with 16 documents in flight, on
its production backend (see scripts/run_timing.py for the full methodology).

ONE DIRECTORY. This used to read two (results/timing and results/timing)
and used their overlap to find the models that had been retimed after the
input-protocol change. The sweeps are now merged on disk, so a retimed model
carries its superseded measurement inside its own file, under
"previous_measurement" - the same delta column, sourced from data rather than
from directory layout.
"""

import argparse
import json
from pathlib import Path

from .main_tables import MODEL_INFO


def load(directory: Path) -> dict:
    out = {}
    if not directory.is_dir():
        return out
    for path in sorted(directory.glob("*.json")):
        if path.name == "query_sample.json":
            continue
        try:
            payload = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        if "mean_seconds" in payload:
            out[path.stem] = payload
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scan", type=Path, default=Path("results/timing"))
    parser.add_argument("--out", type=Path, default=Path("results/tables/RESULTS_timing.md"))
    args = parser.parse_args()

    timings = load(args.scan)
    if not timings:
        raise SystemExit(f"No timing results under {args.scan}")

    rows = []
    for key, entry in timings.items():
        name, category = MODEL_INFO.get(key, (key, "?"))
        previous = entry.get("previous_measurement") or {}
        rows.append(
            {
                "key": key,
                "name": name,
                "category": category,
                "source": "retimed" if previous else "current",
                "mean": entry["mean_seconds"],
                "median": entry["median_seconds"],
                "backend": entry.get("backend", "?"),
                "old_mean": previous.get("mean_seconds"),
                "old_backend": previous.get("backend"),
            }
        )
    rows.sort(key=lambda r: r["median"])

    body = [
        "<!-- Generated by scripts/report_experiments.py. 50 shared queries, 16 documents",
        "     in flight, one H200, production backends. No warmup, so means on the",
        "     ST/pylate paths include a one-time kernel-compile outlier - the medians",
        "     are steady-state and are the number to quote. -->",
        "",
        "# SABER-Math — Per-query latency",
        "",
        "| Model | Category | Src | Backend | Median (s) | Mean (s) | vs previous |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        change = ""
        if row["source"] == "retimed" and row["old_mean"] is not None:
            factor = row["mean"] / row["old_mean"] if row["old_mean"] else 0
            change = f"{factor:.2f}x"
            if row["old_backend"] and row["old_backend"] != row["backend"]:
                change += f" ({row['old_backend']} -> {row['backend']})"
        body.append(
            f"| {row['name']} | {row['category']} | {row['source']} | "
            f"{row['backend']} | {row['median']:.3f} | {row['mean']:.3f} | {change} |"
        )

    changed = [r for r in rows if r["source"] == "retimed"]
    if changed:
        body += [
            "",
            "## Retimed after the input-protocol change",
            "",
            "These are the models whose production inputs changed, so their",
            "previous timings measured a configuration production no longer runs.",
            "",
            "| Model | Previous mean (s) | Current mean (s) | Factor |",
            "|---|---|---|---|",
        ]
        for row in sorted(changed, key=lambda r: r["name"]):
            if row["old_mean"] is None:
                continue
            factor = row["mean"] / row["old_mean"] if row["old_mean"] else 0
            body.append(
                f"| {row['name']} | {row['old_mean']:.3f} | {row['mean']:.3f} | "
                f"{factor:.2f}x |"
            )
        body.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(body))
    print(f"[+] {len(rows)} models ({len(changed)} retimed) -> {args.out}")


if __name__ == "__main__":
    main()
