#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

from sabermath.results import DEFAULT_RESULTS_DIR
from sabermath.tables import MODEL_INFO


TOP_K = [1, 2, 4, 8, 16, 32, 64, 128]

DEDUP_EXCLUDED: dict[str, str] = {}

def load(directory: Path) -> dict:
    out = {}
    for path in sorted(directory.glob("*.json")):
        stem = path.stem
        if "__n" in stem or "smoke" in stem or "selfmatch" in stem:
            continue
        if "candidates-union" in stem:
            continue
        payload = json.loads(path.read_text())
        if "insert_per_query" not in payload:
            continue
        key = payload.get("model") or stem.split("__")[0]
        out[(key, payload.get("regime"))] = payload
    return out

def ndcg_lookup(model_key: str, task: str) -> float | None:
    path = DEFAULT_RESULTS_DIR / f"{model_key}__p0.json"
    if not path.exists():
        return None
    reports = json.loads(path.read_text()).get("reports", {})
    if not reports:
        return None
    for entry in reports[next(iter(reports))].get("tasks", []):
        if entry["task"] == task:
            return entry["ndcg_at_k"]
    return None

def render(rows: list[list[str]]) -> str:
    widths = [max(len(r[i]) for r in rows) for i in range(len(rows[0]))]
    lines = []
    for i, row in enumerate(rows):
        lines.append("| " + " | ".join(c.ljust(widths[j]) for j, c in enumerate(row)) + " |")
        if i == 0:
            lines.append("|" + "|".join("-" * (w + 2) for w in widths))
            lines[-1] += "|"
    return "\n".join(lines)

def regime_table(cells: dict, regime: str) -> tuple[str, list[str]]:
    header = ["Model", "SABER-Math", "Avg. Rank", "Med. Rank"]
    header += [f"Top-{k}" for k in TOP_K]
    rows = [header]

    entries = [
        (model_key, payload)
        for (model_key, cell_regime), payload in cells.items()
        if cell_regime == regime
    ]
    # Median ties heavily at 1.0, so break ties on the mean - the ordering
    # is then total and stable across regenerations.
    entries.sort(
        key=lambda e: (
            e[1]["insert_per_query"]["median_rank"],
            e[1]["insert_per_query"]["avg_rank"],
        )
    )

    for model_key, payload in entries:
        stats = payload["insert_per_query"]
        name = MODEL_INFO.get(model_key, (model_key, ""))[0]
        ndcg = ndcg_lookup(model_key, "statement-statement")
        row = [
            name,
            f"{ndcg:.3f}" if ndcg is not None else "-",
            f"{stats['avg_rank']:.2f}",
            f"{stats['median_rank']:.1f}",
        ]
        row += [f"{stats[f'top_{k}'] * 100:.1f}%" for k in TOP_K]
        rows.append(row)

    covered = {model_key for model_key, _ in entries}
    return render(rows), sorted(covered)

def main(argv=None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scan", type=Path, default=Path("results/dedup"))
    parser.add_argument("--out", type=Path, default=Path("results/tables/RESULTS_dedup.md"))
    args = parser.parse_args(argv)

    cells = load(args.scan)
    if not cells:
        raise SystemExit(f"No dedup results under {args.scan}")

    per_query, per_query_models = regime_table(cells, "per-query-candidates")
    all_docs, all_docs_models = regime_table(cells, "all-documents")

    out = [
        "# Deduplication: where a rephrased copy of the query ranks\n\n",
        f"Source: `{args.scan}`. Generated by `scripts/report_experiments.py`.\n\n",
        "For each of the 1000 queries, an LLM-rephrased copy of that query's\n",
        "own problem is inserted into a corpus and the corpus is ranked by\n",
        "similarity to the original query statement. The reported rank is the\n",
        "position of the inserted copy. **Lower is better.**\n\n",
        "The `SABER-Math` column is **statement-statement** nDCG@10, matching\n",
        "the task setting the dedup vectors are built in - not statement-full,\n",
        "which is a different setting. See docs/experiment-dedup.md.\n\n",
        "---\n\n## 1. Per-query candidates (the published protocol)\n\n",
        "The copy competes against that query's own 150 candidates, ranked\n",
        "among 151. Every model can run this regime.\n\n",
        per_query,
        "\n\n---\n\n## 2. All documents\n\n",
        "The copy competes against all 71,117 documents. A much harder\n",
        "question. Bi-encoders and lexical models only: a pair scorer would\n",
        "need 71,117 forward passes per query.\n\n",
        all_docs,
        "\n\n---\n\n## Notes\n\n",
        "- **Self-match exclusion is a no-op in regime 1.** 92.8% of query\n",
        "  problems appear verbatim in the 71,117-document corpus, so excluding\n",
        "  each query's own original matters a great deal in regime 2. Measured,\n",
        "  **0 of those 928 self-documents fall inside their own query's\n",
        "  150-candidate list**, so regime 1 is unaffected either way.\n",
        "- **What this experiment measures.** The rephrasings preserve the\n",
        "  mathematics and replace the prose: over all 1000 pairs, Jaccard\n",
        "  between a target and its own rephrase is **0.735 on Approach Zero\n",
        "  math tokens but 0.191 on prose words**. Deduplication here is largely\n",
        "  a notation-matching task, which is why BM25 places far above its\n",
        "  retrieval score on it.\n",
        "- `avg_rank` is not the statistic to read: the distribution has a\n",
        "  long tail driven by degenerate query texts, so a handful of\n",
        "  queries move the mean by an order of magnitude. Median and the\n",
        "  top-k coverage are robust.\n",
    ]

    pending = sorted(set(MODEL_INFO) - set(per_query_models) - set(DEDUP_EXCLUDED))
    if pending:
        out.append(
            f"\n### Still running ({len(pending)} of "
            f"{len(MODEL_INFO) - len(DEDUP_EXCLUDED)})\n\n"
        )
        out.append(", ".join(f"`{m}`" for m in pending) + "\n")
    if DEDUP_EXCLUDED:
        out.append("\n### Excluded by design\n\n")
        for model_key, reason in sorted(DEDUP_EXCLUDED.items()):
            out.append(f"- `{model_key}` - {reason}\n")

    text = "".join(out)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(
        f"[+] {args.out}: {len(per_query_models)} models in per-query-candidates, "
        f"{len(all_docs_models)} in all-documents"
    )
    if pending:
        print(f"[~] {len(pending)} model(s) still running: {', '.join(pending)}")

if __name__ == "__main__":
    main()
