#!/usr/bin/env python3
import argparse
from pathlib import Path

from sabermath.results import DEFAULT_RESULTS_DIR
from sabermath.tables import (
    DOMAINS,
    TASKS,
    build_rows,
    collect,
    load_confidence,
    load_timing,
)


def fmt(value) -> str:
    return "-" if value is None else f"{value:.3f}"


def overall_cell(row, task) -> str:
    entry = row.get(task)
    if entry is None:
        return "**TODO**"
    overall = entry[0]
    ci = row.get("ci", {}).get(task)
    if not ci:
        return f"{overall:.3f}"
    lo, hi = ci["interval"]
    return f"{overall:.3f} [{lo:.3f}, {hi:.3f}]"


def table_for_task(rows, task, timing=None) -> str:
    rows = sorted(rows, key=lambda r: -(r.get(task) or (0,))[0])
    header = ["Model", "Cat", "Overall (95% CI)"] + [d.title() for d in DOMAINS]
    if timing is not None:
        header += ["Median (s)"]

    lines = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]

    for row in rows:
        entry = row.get(task)
        cells = [row["name"], row["category"], overall_cell(row, task)]
        cells += ["-"] * len(DOMAINS) if entry is None else [fmt(v) for v in entry[1]]
        if timing is not None:
            t = timing.get(row["key"])
            cells.append(f"{t['median_seconds']:.3f}" if t else "-")
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def confidence_detail(rows) -> list[str]:
    body = []
    for task in TASKS:
        have = [
            r for r in rows
            if r.get("ci", {}).get(task)
            and r.get(task)
            and r["ci"][task].get("branches")
        ]
        if not have:
            continue
        body += [f"## {task}", ""]
        header = ["Model", "Overall"] + [d.title() for d in DOMAINS]
        body += [
            "| " + " | ".join(header) + " |",
            "|" + "|".join("---" for _ in header) + "|",
        ]
        for row in have:
            ci = row["ci"][task]
            lo, hi = ci["interval"]
            cells = [row["name"], f"{row[task][0]:.4f} [{lo:.4f}, {hi:.4f}]"]
            for domain in DOMAINS:
                branch = "calculus and analysis" if domain == "calculus" else domain
                iv = ci["branches"].get(branch)
                cells.append(f"[{iv[0]:.4f}, {iv[1]:.4f}]" if iv else "-")
            body.append("| " + " | ".join(cells) + " |")
        body.append("")
    return body


HEADER_NOTE = """<!--
Generated by scripts/report_experiments.py.

Every row is a production run on the current input protocol, read from
results/evaluation. A model whose run predates that protocol is listed under
"Pending" instead of being shown with a number, because it was produced with a
configuration this repo no longer runs.

Confidence intervals are 95% percentile bootstrap, 10,000 resamples, seed
42411. Only the overall column carries one here; per-domain intervals are in
RESULTS_confidence_intervals.md.

Each model's input envelope and instruction handling are in
src/sabermath/registry.py, beside that model's entry.
-->
"""


def main(argv=None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=DEFAULT_RESULTS_DIR,
        help="Evaluation results. One directory: protocol precedence comes "
        "from each run's own recorded protocol, not from its location.",
    )
    parser.add_argument("--ci-dir", type=Path, default=Path("results/confidence"))
    parser.add_argument("--timing-dir", type=Path, default=Path("results/timing"))
    parser.add_argument("--out-dir", type=Path, default=Path("results/tables"))
    args = parser.parse_args(argv)

    runs, ranks = collect(args.results_dir)
    rows, pending = build_rows(runs, ranks, load_confidence(args.ci_dir))
    timing = load_timing(args.timing_dir)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    files = {
        "RESULTS_main_statement-full.md": (
            "SABER-Math — Statement–Full (main setting)",
            "statement-full",
            timing,
            "The query is a problem statement; each document is a problem "
            "statement plus its solution. This is the setting the paper "
            "reports by default.",
        ),
        "RESULTS_statement-statement.md": (
            "SABER-Math — Statement–Statement",
            "statement-statement",
            None,
            "Queries and documents are both problem statements only — search "
            "over corpora without human-readable solutions.",
        ),
        "RESULTS_full-full.md": (
            "SABER-Math — Full–Full",
            "full-full",
            None,
            "Queries and documents both carry statement plus solution — "
            "retrieval over solved material.",
        ),
    }

    for filename, (title, task, timing_for_table, blurb) in files.items():
        body = [HEADER_NOTE, f"# {title}\n", blurb, "", "All numbers are nDCG@10.\n"]
        body.append(table_for_task(rows, task, timing_for_table))
        body.append("")

        if pending:
            body += [
                "\n## Pending",
                "",
                "No production run on the current input protocol, so no number "
                "is shown:",
                "",
            ]
            body += [f"- **{name}** — {why}" for _, name, why in pending]
            body.append("")

        path = args.out_dir / filename
        path.write_text("\n".join(body))
        written.append(path)

    detail = confidence_detail(rows)
    if detail:
        body = [
            HEADER_NOTE,
            "# SABER-Math — Confidence intervals (recomputed rows)\n",
            "95% percentile bootstrap, 10,000 resamples, seed 42411; domains "
            "resampled at 300 draws, overall at full query count. Produced by "
            "`scripts/analysis/compute_confidence_intervals.py`.\n",
        ] + detail
        path = args.out_dir / "RESULTS_confidence_intervals.md"
        path.write_text("\n".join(body))
        written.append(path)

    print(f"[+] {len(rows)} models on the current protocol")
    for key, name, why in pending:
        print(f"[!] {name} ({key}) omitted: {why}")
    for path in written:
        print(f"[+] Wrote {path}")


if __name__ == "__main__":
    main()
