#!/usr/bin/env python3
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from sabermath.results import DEFAULT_RESULTS_DIR
from sabermath.tables import (
    BRANCH_TO_DOMAIN,
    DOMAINS,
    MODEL_INFO,
    PAPER,
    PAPER_CI_STATEMENT_FULL,
    PAPER_STATEMENT_FULL_ONLY,
    SUPERSEDED_BY_V2,
    TASKS,
    build_rows,
    collect,
    extract_tasks,
    load_confidence,
    load_timing,
)


def fmt(value) -> str:
    return "-" if value is None else f"{value:.3f}"


def delta_note(row) -> str:
    paper = row.get("paper_statement_full")
    if paper is None or row["source"] == "paper" or row["statement-full"] is None:
        return ""
    delta = row["statement-full"][0] - paper
    if abs(delta) < 0.0005:
        return ""
    return f"{delta:+.3f}"


def overall_cell(row, task) -> str:
    entry = row.get(task)
    if entry is None:
        return "**TODO**"
    overall = entry[0]
    ci = row.get("ci", {}).get(task)
    if not ci:
        return f"{overall:.3f}"
    lo, hi = ci["interval"]
    return f"{overall:.3f} [{lo:.3f}, {hi:.3f}]"


def task_sort_key(row, task) -> float:
    entry = row.get(task)
    if entry is not None:
        return entry[0]
    paper = PAPER.get(row["key"])
    if paper is None:
        return 0.0
    return {"statement-full": paper[0], "statement-statement": paper[2],
            "full-full": paper[4]}.get(task, 0.0)


def table_for_task(rows, task, timing=None) -> str:
    rows = sorted(rows, key=lambda r: -task_sort_key(r, task))
    header = ["Model", "Cat", "Src", f"Overall (95% CI)"] + [
        d.title() for d in DOMAINS
    ]
    if task == "statement-full":
        header += ["vs paper"]
    if timing is not None:
        header += ["Median (s)"]

    lines = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]

    for row in rows:
        entry = row.get(task)
        cells = [row["name"], row["category"], row["source"], overall_cell(row, task)]
        if entry is None:
            cells += ["TODO"] * len(DOMAINS)
        else:
            cells += [fmt(v) for v in entry[1]]
        if task == "statement-full":
            cells.append("TODO" if entry is None else (delta_note(row) or ""))
        if timing is not None:
            t = timing.get(row["key"])
            cells.append(f"{t['median_seconds']:.3f}" if t else "-")
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def confidence_detail(rows) -> list[str]:
    body = []
    for task in TASKS:
        # r[task] must exist too, not just the interval: a model can have a
        # bootstrapped CI for a task whose point estimate this table has no
        # source for (a run that finished in one results dir but not the one
        # this table reads), and the row prints the two side by side.
        have = [
            r for r in rows
            if r.get("ci", {}).get(task)
            and r.get(task)
            and not r["ci"][task].get("from_paper")
            and r["ci"][task].get("branches")
        ]
        if not have:
            continue
        body += [f"## {task}", ""]
        header = ["Model", "Src", "Overall"] + [d.title() for d in DOMAINS]
        body += [
            "| " + " | ".join(header) + " |",
            "|" + "|".join("---" for _ in header) + "|",
        ]
        for row in have:
            ci = row["ci"][task]
            lo, hi = ci["interval"]
            cells = [
                row["name"],
                row["source"],
                f"{row[task][0]:.4f} [{lo:.4f}, {hi:.4f}]",
            ]
            for domain in DOMAINS:
                branch = "calculus and analysis" if domain == "calculus" else domain
                iv = ci["branches"].get(branch)
                cells.append(f"[{iv[0]:.4f}, {iv[1]:.4f}]" if iv else "-")
            body.append("| " + " | ".join(cells) + " |")
        body.append("")
    return body


HEADER_NOTE = """<!--
Generated by scripts/report_experiments.py.

Src column:
  v2    - run on the current input protocol (results/evaluation). These rows
          supersede the paper's, and the "vs paper" column gives the change.
  repo  - full 1000-query run on this repo's pipeline (results/evaluation).
  paper - transcribed from the paper's Tables 1 and 4.
  TODO  - the inputs for this model changed and the rerun has NOT landed yet.
          The old number is deliberately not shown: it was produced with a
          configuration we no longer run.

Confidence intervals are 95% percentile bootstrap, 10,000 resamples, seed
42411 - the same estimator that produced the paper's Table 3, so a recomputed
interval is directly comparable to a transcribed one. Only the overall column
carries one here; per-domain intervals for every recomputed row are in
RESULTS_confidence_intervals.md. The paper reports no intervals at all for
statement-statement or full-full, so those tables show intervals only for rows
this repo recomputed.

Protocol changes behind the v2 rows are documented in
docs/protocol.md. Notably:
multilingual-e5-large deliberately keeps our prompt-free configuration
against its model card, and ReasonIR-8B runs on the official remote-code
path rather than vLLM.
-->
"""


def main(argv=None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=DEFAULT_RESULTS_DIR,
        help="Evaluation results. One directory: protocol precedence comes "
        "from each run's own recorded protocol, not from its location.",
    )
    parser.add_argument("--ci-dir", type=Path, default=Path("results/confidence"))
    parser.add_argument("--timing-dir", type=Path, default=Path("results/timing"))
    parser.add_argument("--out-dir", type=Path, default=Path("results/tables"))
    args = parser.parse_args(argv)

    runs, ranks = collect(args.results_dir)
    rows = build_rows(runs, ranks, load_confidence(args.ci_dir))
    timing = load_timing(args.timing_dir)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    files = {
        "RESULTS_main_statement-full.md": (
            "SABER-Math — Statement–Full (main setting)",
            "statement-full",
            timing,
            "The query is a problem statement; each document is a problem "
            "statement plus its solution. This is the setting the paper "
            "reports by default.",
        ),
        "RESULTS_statement-statement.md": (
            "SABER-Math — Statement–Statement",
            "statement-statement",
            None,
            "Queries and documents are both problem statements only — search "
            "over corpora without human-readable solutions.",
        ),
        "RESULTS_full-full.md": (
            "SABER-Math — Full–Full",
            "full-full",
            None,
            "Queries and documents both carry statement plus solution — "
            "retrieval over solved material.",
        ),
    }

    for filename, (title, task, timing_for_table, blurb) in files.items():
        body = [HEADER_NOTE, f"# {title}\n", blurb, "", "All numbers are nDCG@10.\n"]
        body.append(table_for_task(rows, task, timing_for_table))
        body.append("")

        todo = [r for r in rows if r.get("todo")]
        if todo:
            body += [
                "\n## Outstanding",
                "",
                "These models' inputs changed and the rerun has not landed yet, "
                "so no number is shown for them:",
                "",
            ]
            for row in todo:
                paper = row.get("paper_statement_full")
                was = f" (paper had {paper:.3f} on statement-full)" if paper else ""
                body.append(f"- **TODO {row['name']}**{was}")
            body.append("")

        changed = [r for r in rows if r["source"] == "v2"]
        if changed and task == "statement-full":
            body += ["\n## Rows that changed", "",
                     "| Model | Paper | Current (95% CI) | Delta |", "|---|---|---|---|"]
            for row in sorted(changed, key=lambda r: r["name"]):
                paper = row.get("paper_statement_full")
                if paper is None:
                    delta = "new row"
                else:
                    delta = delta_note(row) or "0.000"
                body.append(
                    f"| {row['name']} | {fmt(paper)} | {overall_cell(row, task)} | "
                    f"{delta} |"
                )
            body.append("")

        path = args.out_dir / filename
        path.write_text("\n".join(body))
        written.append(path)

    detail = confidence_detail(rows)
    if detail:
        body = [
            HEADER_NOTE,
            "# SABER-Math — Confidence intervals (recomputed rows)\n",
            "95% percentile bootstrap, 10,000 resamples, seed 42411; domains "
            "resampled at 300 draws, overall at full query count. Produced by "
            "`python -m sabermath.analysis.compute_confidence_intervals`.\n",
        ] + detail
        path = args.out_dir / "RESULTS_confidence_intervals.md"
        path.write_text("\n".join(body))
        written.append(path)

    counts = {}
    for row in rows:
        counts[row["source"]] = counts.get(row["source"], 0) + 1
    print(
        f"[+] {len(rows)} models: "
        + ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))
    )
    for path in written:
        print(f"[+] Wrote {path}")


if __name__ == "__main__":
    main()
