#!/usr/bin/env python3
"""Equations vs. prose, per instruction arm.

For every method and every instruction arm, the share of targets whose
equation-only representation scores closer to the target's five most relevant
candidates than its word-only representation does. The figure
(`scripts/plots/plot_math_vs_word.py`) plots this per domain; this prints it.

Both read `results/math_vs_word/similarities/` through
`sabermath.math_vs_word.aggregate`, so the figure and the table cannot come to
different numbers. This is the table the paper reports as its per-instruction
math-vs-word breakdown; see docs/experiment-math-vs-word.md.

    python scripts/tables/math_vs_word_table.py                # md + csv + tex
    python scripts/tables/math_vs_word_table.py --overall-only  # no datasets

The per-domain columns of the CSV need the targets dataset, for the domain of
each target; `--overall-only` skips them, and the printed table (which has no
per-domain columns) is unaffected either way.
"""

import argparse
import csv
from pathlib import Path

import yaml

from sabermath.figures import DEFAULT_MODEL_DISPLAY_NAMES
from sabermath.math_vs_word import SIMILARITIES_DIR
from sabermath.math_vs_word.aggregate import (
    ARMS,
    DOMAIN_ORDER,
    NON_EMBEDDING_METHODS,
    aggregate_math_vs_words,
    arms_on_disk,
    build_id_to_domain,
    load_similarity_content,
)
from sabermath.math_vs_word.roster import all_methods

CONFIG_DIR = Path(__file__).resolve().parents[1] / "config"
DEFAULT_CONFIG = CONFIG_DIR / "math_vs_word.yaml"

DEFAULT_OUT_MD = Path("results/tables/RESULTS_math_vs_word.md")
DEFAULT_OUT_CSV = Path("results/math_vs_word/results_table.csv")
DEFAULT_OUT_TEX = Path("results/tables/math_vs_word_instructions.tex")

ARM_LABELS = {"p0": "No Instr.", "p1": "I1", "p2": "I2", "p3": "I3"}

CSV_FIELDS = (
    ["method", "arm", "n_targets", "ties_skipped", "pct_math_gt_words_All"]
    + [f"pct_{domain}" for domain in DOMAIN_ORDER]
    + ["mean_pr_full", "mean_pr_math", "mean_pr_text"]
)

HEADER_NOTE = """<!--
Generated by scripts/report_experiments.py (or
scripts/tables/math_vs_word_table.py), from
results/math_vs_word/similarities/.

Each cell is the percentage of targets whose equation-only representation is
more similar to the target's five most relevant candidates than its word-only
representation is - the quantity plotted per domain in the math-vs-word
figure. Higher means the method leans on notation; lower means it leans on
prose.

Arms are the instruction prompts of docs/experiment-instructions.md, applied
to the query only. p0 (no instruction, full vendor input envelope) is stored
unsuffixed, so `<method>.json` and `<method>__p0.json` are the same run.

Approach Zero, BM25, Jaccard and TF-IDF have no instruction mechanism and are
the ablation's controls: they appear in the CSV at p0 and are omitted from the
table below, as in the paper.
-->
"""


def display_name(model_id: str) -> str:
    if model_id in DEFAULT_MODEL_DISPLAY_NAMES:
        return DEFAULT_MODEL_DISPLAY_NAMES[model_id]
    return model_id.rsplit("/", 1)[-1]


def fmt_pct(value: float | None) -> str:
    if value is None or value != value:  # missing, or NaN
        return "-"
    return f"{value:.1f}"


def collect(sim_dir: Path, methods: list[str], id_to_domain=None) -> dict:
    """(method, arm) -> MathVsWordStats, for every arm present on disk."""
    stats = {}
    for model_id, arms in arms_on_disk(methods, sim_dir).items():
        for arm in arms:
            content = load_similarity_content(model_id, arm, sim_dir)
            stats[(model_id, arm)] = aggregate_math_vs_words(
                content, model_id=model_id, id_to_domain=id_to_domain
            )
    return stats


def ordered_methods(stats: dict, methods: list[str]) -> list[str]:
    """Instructable methods, best baseline first - the paper's ordering."""
    rows = [
        model_id
        for model_id in methods
        if model_id not in NON_EMBEDDING_METHODS
        and any((model_id, arm) in stats for arm in ARMS)
    ]
    return sorted(
        rows,
        key=lambda model_id: -(
            stats[(model_id, "p0")].percentages["All"]
            if (model_id, "p0") in stats
            else float("-inf")
        ),
    )


def markdown(stats: dict, ordered: list[str], missing: list[str]) -> str:
    body = [
        HEADER_NOTE,
        "# Math vs. words, by instruction arm",
        "",
        "Percentage of targets where the equation-only representation is more "
        "similar to the relevant candidates than the word-only representation "
        "(M>W, all domains).",
        "",
        "| Model | " + " | ".join(ARM_LABELS[arm] for arm in ARMS) + " |",
        "|---|" + "|".join("---" for _ in ARMS) + "|",
    ]
    for model_id in ordered:
        cells = [
            fmt_pct(
                stats[(model_id, arm)].percentages["All"]
                if (model_id, arm) in stats
                else None
            )
            for arm in ARMS
        ]
        body.append(f"| {display_name(model_id)} | " + " | ".join(cells) + " |")

    controls = sorted(
        model_id
        for model_id in NON_EMBEDDING_METHODS
        if (model_id, "p0") in stats
    )
    if controls:
        body += ["", "## Instruction controls (no instruction mechanism)", ""]
        body += ["| Model | No Instr. |", "|---|---|"]
        for model_id in controls:
            pct = stats[(model_id, "p0")].percentages["All"]
            body.append(f"| {display_name(model_id)} | {fmt_pct(pct)} |")

    if missing:
        body += ["", "## Not run", ""]
        body += [f"- {model_id}" for model_id in missing]

    ties = sorted(
        (model_id, arm, entry.ties_skipped)
        for (model_id, arm), entry in stats.items()
        if entry.ties_skipped
    )
    if ties:
        body += [
            "",
            "## Tied targets, excluded from the percentages",
            "",
            "A tie is a target the method scored identically under both "
            "representations. Only the systems that quantise or rewrite can "
            "produce one; anywhere else it raises.",
            "",
            "| Model | Arm | Ties |",
            "|---|---|---|",
        ]
        for model_id, arm, n in ties:
            body.append(f"| {display_name(model_id)} | {arm} | {n} |")

    return "\n".join(body) + "\n"


def latex(stats: dict, ordered: list[str]) -> str:
    lines = [
        r"% Generated by scripts/tables/math_vs_word_table.py.",
        r"\begin{tabular}{l" + "r" * len(ARMS) + "}",
        r"\toprule",
        "Model & " + " & ".join(ARM_LABELS[arm] for arm in ARMS) + r" \\",
        r"\midrule",
    ]
    for model_id in ordered:
        cells = [
            fmt_pct(
                stats[(model_id, arm)].percentages["All"]
                if (model_id, arm) in stats
                else None
            )
            for arm in ARMS
        ]
        name = display_name(model_id).replace("&", r"\&")
        lines.append(f"{name} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def write_csv(stats: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        writer.writeheader()
        for (model_id, arm), entry in sorted(stats.items()):
            row = {
                "method": model_id,
                "arm": arm,
                "n_targets": entry.n_targets,
                "ties_skipped": entry.ties_skipped,
                "pct_math_gt_words_All": round(entry.percentages["All"], 2),
            }
            for domain in DOMAIN_ORDER:
                value = entry.percentages[domain]
                row[f"pct_{domain}"] = (
                    "" if value != value else round(value, 2)
                )
            row["mean_pr_full"] = round(entry.mean_pr["pr_full_vs_candidates"], 4)
            row["mean_pr_math"] = round(entry.mean_pr["pr_math_vs_candidates"], 4)
            row["mean_pr_text"] = round(entry.mean_pr["pr_text_vs_candidates"], 4)
            writer.writerow(row)


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(
        description=__doc__.split("\n")[0],
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--sim-dir", type=Path, default=SIMILARITIES_DIR)
    parser.add_argument("--config-file", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument(
        "--overall-only",
        action="store_true",
        help="Skip the per-domain CSV columns, which are the only part that "
        "needs the targets dataset.",
    )
    parser.add_argument(
        "--methods",
        nargs="*",
        default=None,
        help="Restrict to these methods (default: the whole roster).",
    )
    parser.add_argument("--out-md", type=Path, default=DEFAULT_OUT_MD)
    parser.add_argument("--out-csv", type=Path, default=DEFAULT_OUT_CSV)
    parser.add_argument("--out-tex", type=Path, default=DEFAULT_OUT_TEX)
    args = parser.parse_args(argv)

    methods = args.methods or all_methods()

    present = arms_on_disk(methods, args.sim_dir)
    if not present:
        raise SystemExit(
            f"No similarity files in {args.sim_dir} - run "
            f"scripts/analysis/math_vs_word.py first."
        )

    id_to_domain = None
    if not args.overall_only:
        config = yaml.safe_load(args.config_file.read_text()) or {}
        targets_dataset = config["hf_datasets"]["targets_maths_words_fixed"]
        all_content_ids = set()
        for model_id, arms in present.items():
            content = load_similarity_content(model_id, arms[0], args.sim_dir)
            all_content_ids.update(str(target_id) for target_id in content)
        id_to_domain = build_id_to_domain(
            all_content_ids=all_content_ids,
            targets_dataset_name=targets_dataset,
        )

    stats = collect(args.sim_dir, methods, id_to_domain)
    ordered = ordered_methods(stats, methods)
    missing = [model_id for model_id in methods if model_id not in present]

    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(markdown(stats, ordered, missing))
    print(f"[+] Wrote {args.out_md}")

    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(latex(stats, ordered))
    print(f"[+] Wrote {args.out_tex}")

    write_csv(stats, args.out_csv)
    print(f"[+] Wrote {args.out_csv}")

    arm_counts = {
        arm: sum(1 for (_, cell_arm) in stats if cell_arm == arm) for arm in ARMS
    }
    print(
        f"[+] {len(present)} methods, "
        + ", ".join(f"{n} {arm}" for arm, n in arm_counts.items())
        + (" (per-domain columns skipped)" if args.overall_only else "")
    )
    if missing:
        print(f"[~] {len(missing)} roster methods with no run: {', '.join(missing)}")


if __name__ == "__main__":
    main()
