#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

from sabermath.tables import MODEL_INFO


def load(directory: Path) -> dict:
    out = {}
    if not directory.is_dir():
        return out
    for path in sorted(directory.glob("*.json")):
        if path.name == "query_sample.json":
            continue
        try:
            payload = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            continue
        if "mean_seconds" in payload:
            out[path.stem] = payload
    return out

def main(argv=None) -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scan", type=Path, default=Path("results/timing"))
    parser.add_argument("--out", type=Path, default=Path("results/tables/RESULTS_timing.md"))
    args = parser.parse_args(argv)

    timings = load(args.scan)
    if not timings:
        raise SystemExit(f"No timing results under {args.scan}")

    rows = []
    for key, entry in timings.items():
        name, category = MODEL_INFO.get(key, (key, "?"))
        rows.append(
            {
                "key": key,
                "name": name,
                "category": category,
                "mean": entry["mean_seconds"],
                "median": entry["median_seconds"],
                "backend": entry.get("backend", "?"),
            }
        )
    rows.sort(key=lambda r: r["median"])

    body = [
        "<!-- Generated by scripts/report_experiments.py. 50 shared queries, 16 documents",
        "     in flight, one H200, production backends. No warmup, so means on the",
        "     ST/pylate paths include a one-time kernel-compile outlier - the medians",
        "     are steady-state and are the number to quote. -->",
        "",
        "# SABER-Math — Per-query latency",
        "",
        "| Model | Category | Backend | Median (s) | Mean (s) |",
        "|---|---|---|---|---|",
    ]
    for row in rows:
        body.append(
            f"| {row['name']} | {row['category']} | {row['backend']} | "
            f"{row['median']:.3f} | {row['mean']:.3f} |"
        )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(body))
    print(f"[+] {len(rows)} models -> {args.out}")

if __name__ == "__main__":
    main()
