ALLOWED_MODELS = [
    "Qwen/Qwen3-Embedding-8B",
    "Qwen/Qwen3-Embedding-4B",
    "Qwen/Qwen3-Embedding-0.6B",
    "BAAI/bge-m3",
    "tencent/KaLM-Embedding-Gemma3-12B-2511",
    "google/embeddinggemma-300m",
    "google-bert/bert-base-uncased",
    "FacebookAI/roberta-base",
    "microsoft/codebert-base",
    "google/gemini-embedding-001",
    "google/gemini-embedding-2",
    "microsoft/harrier-oss-v1-0.6b",
    "microsoft/harrier-oss-v1-270m",
    "microsoft/harrier-oss-v1-27b",
    "Octen/Octen-Embedding-4B",
    "Octen/Octen-Embedding-8B",
    "jinaai/jina-embeddings-v5-text-nano",
    "jinaai/jina-embeddings-v5-text-small",
    "hanhainebula/reason-embed-qwen3-8b-0928",
    "hanhainebula/reason-embed-llama-3.1-8b-0928",
    "AQ-MedAI/Diver-Retriever-4B",
    "AQ-MedAI/Diver-Retriever-0.6B",
    "infly/inf-retriever-v1-pro",
    "reasonir/ReasonIR-8B",
    "Raderspace/RaDeR_Qwen25-14B_NuminaMath_MATH_allquerytypes",
    "Raderspace/RaDeR_Qwen25-7B_NuminaMath_MATH_allquerytypes",
    "Raderspace/RaDeR_Qwen25_3B_NuminaMath_MATH_allquerytypes",
    "nvidia/llama-embed-nemotron-8b",
    "intfloat/multilingual-e5-large",
    "text-embedding-3-large",
    "text-embedding-3-small",
    "jhu-clsp/rank1-32b",
    "jhu-clsp/rank1-7b",
    "jhu-clsp/rank1-0.5b",
    "qwen3-reranker-8b",
    "qwen3-reranker-4b",
    "qwen3-reranker-0.6b",
    "splade-code-8b",
    "splade-code-0.6b",
    "rader-reranker-7b",
    "diver-grouprank-32b",
    "lightonai/GTE-ModernColBERT-v1",
    "lightonai/Reason-ModernColBERT",
    "inf-x-retriever",
    "retro-star-32b",
    "retro-star-32b-rewritten",
    "reason-rewriter-reason-embed-8b",
    "reason-rewriter-reason-embed-llama-3.1-8b",
]

LEXICAL_METHODS = ["bm25", "tf-idf", "jaccard", "approach0"]


def all_methods() -> list[str]:
    return list(ALLOWED_MODELS) + LEXICAL_METHODS
